propriedades = dict()
propriedades['ballon stand']      = {'owner':None, 'price':1, 'pay':1}
propriedades['corron stand']      = {'owner':None, 'price':1, 'pay':1}
propriedades['puppet show']       = {'owner':None, 'price':2, 'pay':2}
propriedades['magic show']        = {'owner':None, 'price':2, 'pay':2}
propriedades['merry-go round']    = {'owner':None, 'price':2, 'pay':2}
propriedades['paddle boats']      = {'owner':None, 'price':2, 'pay':2}
propriedades['water slide']       = {'owner':None, 'price':3, 'pay':3}
propriedades['mini golf']         = {'owner':None, 'price':3, 'pay':3}
propriedades['video arcade']      = {'owner':None, 'price':3, 'pay':3}
propriedades['haunted house']     = {'owner':None, 'price':3, 'pay':3}
propriedades['helicopter ride']   = {'owner':None, 'price':4, 'pay':4}
propriedades['pony ride']         = {'owner':None, 'price':4, 'pay':4}
propriedades['bumber cars']       = {'owner':None, 'price':4, 'pay':4}
propriedades['ferris wheel']      = {'owner':None, 'price':4, 'pay':4}
propriedades['loop the loop']     = {'owner':None, 'price':5, 'pay':5}
propriedades['roller coaster']    = {'owner':None, 'price':5, 'pay':5}